---
- hosts: all
  tasks:
  - name: Install pip
    apt: 
       name: python3-pip 
       state:  present
    become: yes    

  - name: Install Flask
    command: pip3 install -U Flask
    become: yes   

  - name: Create app 
    become: yes
    copy:
      dest: "/home/vagrant/hello.py"
      content: |

        from flask import Flask

        app = Flask(__name__)


        @app.route('/')
        def index():

            return "Hello from IP" 

        if __name__ == '__main__':
                    app.run(debug = True, host='0.0.0.0', port='5000')


  - name: Get IP and insert in the app  
    shell: sed -i "s/IP/$(hostname)/g" /home/vagrant/hello.py
    become: yes

  - name: Create a service for the app   
    become: yes
    copy:
      dest: "/etc/systemd/system/app.service"
      mode: 0664 
      owner: vagrant 
      content: | 
        [Unit]
        Description=Flask application

        [Service]
        ExecStart=/usr/bin/python3 /home/vagrant/hello.py

        [Install]
        WantedBy=multi-user.target

  - name: Start app 
    become: yes
    systemd:   
      state: started 
      daemon_reload: yes 
      name: app.service
      enabled: yes
